import { execFileSync, spawn, type ChildProcess } from "node:child_process";
import { createServer, type Server } from "node:http";
import { chmodSync, copyFileSync, mkdirSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const root = process.cwd();
const databasePort = "54329";
const webPort = "18080";
const capturePort = "18081";
const containerName = `bookmarker-e2e-${process.pid}`;
const databaseURL = `postgresql://bookmarker:bookmarker-test@127.0.0.1:${databasePort}/bookmarker?sslmode=disable`;
const runtimeConfig = join(root, ".e2e-config.yaml");
const templateConfig = join(root, ".e2e-config.template.yaml");
const screenshots = join(root, ".e2e-screenshots");

export default async function globalSetup() {
  process.env.BOOKMARKER_CAPTURE_BASE_URL = `http://127.0.0.1:${capturePort}`;
  execFileSync("docker", ["run", "--detach", "--rm", "--name", containerName, "--publish", `${databasePort}:5432`, "--env", "POSTGRES_DB=bookmarker", "--env", "POSTGRES_USER=bookmarker", "--env", "POSTGRES_PASSWORD=bookmarker-test", "postgres:18.6"], { stdio: "inherit" });
  await waitForDatabase();
  execFileSync("psql", [databaseURL, "-v", "ON_ERROR_STOP=1", "-f", join(root, "migrations/0001_bookmarks.up.sql")], { stdio: "inherit" });

  mkdirSync(screenshots, { recursive: true });
  writeRuntimeConfig();
  const captureServer = startCaptureServer();
  const web = startWebServer();
  await waitForWeb();

  return async () => {
    await new Promise<void>((resolve) => captureServer.close(() => resolve()));
    stop(web);
    rmSync(runtimeConfig, { force: true });
    rmSync(templateConfig, { force: true });
    rmSync(screenshots, { recursive: true, force: true });
    execFileSync("docker", ["stop", containerName], { stdio: "inherit" });
  };
}

function writeRuntimeConfig() {
  const config = `# Generated by Playwright global setup.\nadministrator:\n  username: admin\n  password_hash: $argon2id$v=19$m=65536,t=3,p=1$C9O9Mk4c2Zn/ZfyqxooQvA$HPd9+zneNgxejjew94cvrd8E8+MwuZcPhibe4x1i0vM\nbranding:\n  page_title: Bookmarker (E2E)\n  favicon_path: \"\"\ndefault_view: list\nscreenshots:\n  root: ${screenshots}\ndatabase:\n  host: 127.0.0.1\n  port: ${databasePort}\n  name: bookmarker\n  user: bookmarker\n  password_env: BOOKMARKER_DB_PASSWORD\n  tls_mode: disable\nsearch:\n  page_size: 10\n  maximum_results: 10000\nserver:\n  listen_address: 127.0.0.1:${webPort}\n  trusted_proxy_cidrs: []\n`;
  writeFileSync(templateConfig, config, { mode: 0o600 });
  copyFileSync(templateConfig, runtimeConfig);
  chmodSync(runtimeConfig, 0o600);
}

function startCaptureServer() {
  const server = createServer((request, response) => {
    if (request.url === "/capture-target") {
      response.writeHead(200, { "Content-Type": "text/html; charset=utf-8" });
      response.end("<!doctype html><title>Capture fixture</title><h1>Capture fixture</h1>");
      return;
    }
    if (request.url === "/capture-target/unreachable") {
      request.socket.destroy();
      return;
    }
    response.writeHead(404).end();
  });
  server.listen(Number(capturePort), "127.0.0.1");
  return server;
}

function startWebServer() {
  return spawn("go", ["run", "./cmd/bookmarker-web"], {
    cwd: root,
    env: {
      ...process.env,
      BOOKMARKER_CAPTURE_BASE_URL: `http://127.0.0.1:${capturePort}`,
      BOOKMARKER_CONFIG: runtimeConfig,
      BOOKMARKER_DB_PASSWORD: "bookmarker-test",
    },
    stdio: "inherit",
    detached: true,
  });
}

async function waitForDatabase() {
  for (let attempt = 0; attempt < 30; attempt++) {
    try {
      execFileSync("pg_isready", ["--host", "127.0.0.1", "--port", databasePort, "--username", "bookmarker", "--dbname", "bookmarker"], { stdio: "ignore" });
      return;
    } catch {
      await new Promise((resolve) => setTimeout(resolve, 500));
    }
  }
  throw new Error("E2E PostgreSQL did not become ready");
}

async function waitForWeb() {
  for (let attempt = 0; attempt < 60; attempt++) {
    try {
      const response = await fetch(`http://127.0.0.1:${webPort}/bookmarks`);
      if (response.ok) return;
    } catch {
      // The process is still starting.
    }
    await new Promise((resolve) => setTimeout(resolve, 250));
  }
  throw new Error("E2E Bookmarker server did not become ready");
}

function stop(process: ChildProcess) {
  if (process.pid !== undefined) globalThis.process.kill(-process.pid, "SIGTERM");
}